#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -cursor_name right_ptr

redshift -P -O 4500 &
kitty &

xinput set-button-map 11 3 2 1 &

bspc monitor -d I II III IV 

bspc config border_width         2
bspc config window_gap         	 6 

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
