#include <stdio.h>

int main() {
    printf(
    "\n--------------------------------------------------------------------------\n"
    "\n                           Documentation for RBS\n\n"
    "\tThere are 2 logins \n\n\tA. Admin\n\tB. User\n\n\tC. End program\n"
    "\tD. Documentation\n"
    "\tA. Admin has 4 powers\n"
    "\t\t1. Create room\n\t\t2. Remove room\n\t\t3. Display room\n\t\t4. Exit to login"
    " page\n"
    "\n\t1. Create room - This is of the most powerfull one. You can create "
    "\n\tany no of rooms that you want. The only limit is your processor."
    "\n\tpower\n"
    "\n\n\t** There is 15 rooms already created at first: "
    "\n\t8 - Deluxe, 7 - Double **\n"
    "\n\n\t2. Remove room - Another functionality. You can remove any room \n"
    "\tjust by specifying the room no. It's that simple\n"
    "\n\t3. Display room\n\n"
    "\tIt is present in both admin and user and also used throughout the" 
    "\n\tprogram\n"
    "\tIt has three options\n\n"
    "\tDisplay:\n"
    "\t\tAll rooms\n\t\tsingle room - using room no\n\t\tAvailable rooms only\n\n\n"
    "\tB. User also has 4 powers\n"
    "\t\t1. Book room\n\t\t2. Vacate room\n\t\t3. Display room\n\t\t4. Exit to login"
    " page\n\n"
    "\t1. Book room - Booking rooms is as simple as entering the no of" 
    "\n\tdeluxe and \n"
    "\tno of double rooms required.\n\n"
    "\tYou can find the nearest rooms to the location you give or just" 
    "\n\trandom rooms\n"
    "\tavailable. It's entirely your choice\n\n"
    "\t2. Vacate room - Enter the room no you want to vacate and" 
    "\n\tit's done.\n\n"
    "\n\tIn every menu or options shown you are given option to exit out" 
    "\n\tof it.\n"
    "\tIn login page you have the option to end the program.\n\n"
    "\n--------------------------------------------------------------------------\n\n"
    );
}
