#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -solid "#000000"
xsetroot -cursor_name left_ptr

redshift -P -O 4500 &
kitty &

xinput set-button-map 11 3 2 1 & 
xset -dpms &
xset s off &

bspc monitor -d I II III IV

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
